default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: dnd_maps_browser_server_development
  username: postgres
  password: 5432

test:
  <<: *default
  database: dnd_maps_browser_server_test
  username: postgres
  password: 5432
